profile_name: base_plus_1024_gpu1
llm_name: extracted_weights/lvlm/xsam_siglip2_hf
seg_encoder_name: sam2.1-hiera-base-plus
s1_pretrained_relpath: s1_seg_finetune/xsam_sam2_base_1024_e3_gpu1_seg_finetune_v1/pytorch_model.bin
visual_encoder_pretrained_relpath: extracted_weights/img_encoder/xsam_img_encoder.bin
projector_pretrained_candidates:
  - s2_align_pretrain/xsam_phi3_mini_4k_instruct_siglip2_so400m_p14_384_sam2_base_e1_gpu1_align_pretrain_1024_v2/pytorch_model.bin
  - s2_align_pretrain/xsam_phi3_mini_4k_instruct_siglip2_so400m_p14_384_sam2_base_plus_1024_m2f_gpu2_mixed_finetune_v2/pytorch_model.bin
  - s2_align_pretrain/xsam_phi3_mini_4k_instruct_siglip2_so400m_p14_384_sam2_base_e1_gpu1_align_pretrain_768/pytorch_model.bin
llm_projector_pretrained_relpath: extracted_weights/projectors/llm_projector/xsam_s3_llm_projectors.bin
s2_pretrained_relpath: null
segmentor_trunk_mode: full_ft
segmentor_fpn_mode: full_ft
segmentor_lora_rank: 16
segmentor_lora_alpha: 32
segmentor_lora_dropout: 0.05
segmentor_lora_bias: none
segmentor_lora_target_modules: null
prompt_template: phi3_chat
max_length: 2319
batch_size: 8
accumulative_counts: 16
dataloader_num_workers: 8
max_epochs: 0.25
lr: 4.0e-5
betas: [0.9, 0.999]
weight_decay: 0.05
max_norm: 1.0
warmup_ratio: 0.03
enable_lora: true
enable_4bit_llm: true
freeze_llm: true
connector_type: null
llm_attn_implementation: flash_attention_2
seg_attn_implementation: flash_attention_2
llava_split_mode: split
persistent_workers: true
use_train_ratio: true
save_steps: 2000
save_total_limit: 2
logging_interval: 10
evaluation_freq: 2000
