profile_name: qwen3_1x7b
llm_name: Qwen3-1.7B
prompt_template: qwen3_wothinking
max_length: 39183
enable_4bit_llm: false
s1_pretrained_relpath: s1_seg_finetune/xsam_sam_large_m2f_e36_gpu16_seg_finetune/pytorch_model.bin
segmentor_trunk_mode: freeze
segmentor_fpn_mode: freeze
segmentor_lora_rank: 16
segmentor_lora_alpha: 32
segmentor_lora_dropout: 0.05
segmentor_lora_bias: none
segmentor_lora_target_modules: null
batch_size: 4
accumulative_counts: 4
dataloader_num_workers: 8
max_epochs: 1
lr: 1.0e-3
weight_decay: 0.0
max_norm: 1.0
warmup_ratio: 0.03
save_steps: 2000
save_total_limit: 2
logging_interval: 10
evaluation_freq: 2000
